name: Deploy automático

on:
  push:
    branches:
      - main  # branch que dispara o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.119.192.186 >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy no servidor via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@18.119.192.186 << 'EOF'
            cd /var/www/felipedev.website || exit 1
            git pull origin main
            npm install
            npm run build
            pm2 restart app || true
          EOF
        shell: bash
